name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generate the snake gif and svg
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: teja-pola

      # Commit and push the changes
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake gif and svg"
          branch: output
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"

      # Deploy to GitHub Pages (optional)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
